// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exemplu.Models;

#nullable disable

namespace exemplu.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exemplu.Models.CONCURENT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CONCURSId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataNasterii")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tara")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Varsta")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CONCURSId");

                    b.ToTable("CONCURENTI", (string)null);
                });

            modelBuilder.Entity("exemplu.Models.CONCURS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Data")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("nr_max_participanti")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("restrictie_varsta")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CONCURSURI", (string)null);
                });

            modelBuilder.Entity("exemplu.Models.CONCURENT", b =>
                {
                    b.HasOne("exemplu.Models.CONCURS", "CONCURS")
                        .WithMany("CONCURENTI")
                        .HasForeignKey("CONCURSId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CONCURS");
                });

            modelBuilder.Entity("exemplu.Models.CONCURS", b =>
                {
                    b.Navigation("CONCURENTI");
                });
#pragma warning restore 612, 618
        }
    }
}
